export const LoginTypes = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    USER_LOGOUT: "USER_LOGOUT",
};

export const EnvironmentTypes = {
    GETENVIRONMENT_REQUEST: "GETENVIRONMENT_REQUEST",
    GETENVIRONMENT_SUCCESS: "GETENVIRONMENT_SUCCESS",
    GETENVIRONMENT_FAILURE: "GETENVIRONMENT_FAILURE",

    GETENVIRONMENTS_REQUEST: "GETENVIRONMENTS_REQUEST",
    GETENVIRONMENTS_SUCCESS: "GETENVIRONMENTS_SUCCESS",
    GETENVIRONMENTS_FAILURE: "GETENVIRONMENTS_FAILURE",

    CREATEENVIRONMENT_REQUEST: "CREATEENVIRONMENT_REQUEST",
    CREATEENVIRONMENT_SUCCESS: "CREATEENVIRONMENT_SUCCESS",
    CREATEENVIRONMENT_FAILURE: "CREATEENVIRONMENT_FAILURE",

    UPDATEENVIRONMENT_REQUEST: "UPDATEENVIRONMENT_REQUEST",
    UPDATEENVIRONMENT_SUCCESS: "UPDATEENVIRONMENT_SUCCESS",
    UPDATEENVIRONMENT_FAILURE: "UPDATEENVIRONMENT_FAILURE",

    DELETEENVIRONMENT_REQUEST: "DELETEENVIRONMENT_REQUEST",
    DELETEENVIRONMENT_SUCCESS: "DELETEENVIRONMENT_SUCCESS",
    DELETEENVIRONMENT_FAILURE: "DELETEENVIRONMENT_FAILURE",
};
